services:
  db:
    image: mysql:latest
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.example
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
